server:
  port: 8000

spring:
  application:
    name: sharding-sphere
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 142857
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds2?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 142857
    # 分库分表规则
    sharding:
      tables:
        user:
          # ds0~1-->user_0~user_2  ds1~1-->user_0~user_2  相当于两个库 六张表
          actual-data-nodes: ds$->{0..1}.user_$->{0..2},dss$->{0..1}.user_$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 3}
        order:
          actual-data-nodes: ds$->{0..1}.order_$->{0..2},dss$->{0..1}.order_$->{0..2}
          table-strategy:
            inline:
              sharding-column: id

logging:
  pattern:
    file: time=%date{yyyy-MM-dd HH:mm:ss.SSS}, level=%p, thread=%t, logger=%logger{0}, %X, %replace(message=[%msg]){'[\r\n]+', ''}%n
    console: time=%date{yyyy-MM-dd HH:mm:ss.SSS}, %highlight(level=%p), %green(thread=%t), %cyan(logger=%logger{0}), %X, %replace(message=[%msg]){'[\r\n]+', ''}%n
