server:
  port: 8000

spring:
  application:
    name: sharding-sphere
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds1,ds2
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxxxx:3306/ds1?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxxxx:3306/ds2?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root

logging:
  pattern:
    file: time=%date{yyyy-MM-dd HH:mm:ss.SSS}, level=%p, thread=%t, logger=%logger{0}, %X, %replace(message=[%msg]){'[\r\n]+', ''}%n
    console: time=%date{yyyy-MM-dd HH:mm:ss.SSS}, %highlight(level=%p), %green(thread=%t), %cyan(logger=%logger{0}), %X, %replace(message=[%msg]){'[\r\n]+', ''}%n
