// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: justtest.proto

package cn.cocowwy.grpcjava.heartdemo.api;

public interface RPCDateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.cocowwy.grpcserver.api.RPCDateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serverDate = 1;</code>
   */
  java.lang.String getServerDate();
  /**
   * <code>optional string serverDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerDateBytes();
}
