// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart.proto

package cn.cocowwy.grpcjava.heartdemo.heart;

public final class GRPCHeart {
  private GRPCHeart() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_cocowwy_heart_HeartReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_cocowwy_heart_HeartReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_cocowwy_heart_HeartResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_cocowwy_heart_HeartResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013heart.proto\022\020cn.cocowwy.heart\"C\n\010Heart" +
      "Req\022\020\n\010serverId\030\001 \001(\005\022\022\n\nserverName\030\002 \001(" +
      "\t\022\021\n\ttimestamp\030\003 \001(\005\"\030\n\tHeartResp\022\013\n\003res" +
      "\030\001 \001(\0102^\n\022HeartReportService\022H\n\013handleHe" +
      "art\022\032.cn.cocowwy.heart.HeartReq\032\033.cn.coc" +
      "owwy.heart.HeartResp\"\000B\037\n\020cn.cocowwy.hea" +
      "rtB\tGRPCHeartP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_cocowwy_heart_HeartReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_cocowwy_heart_HeartReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_cocowwy_heart_HeartReq_descriptor,
        new java.lang.String[] { "ServerId", "ServerName", "Timestamp", });
    internal_static_cn_cocowwy_heart_HeartResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_cocowwy_heart_HeartResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_cocowwy_heart_HeartResp_descriptor,
        new java.lang.String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
