// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart.proto

package cn.cocowwy.grpcjava.heartdemo.heart;

public interface HeartRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.cocowwy.heart.HeartResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool res = 1;</code>
   */
  boolean getRes();
}
