// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart.proto

package cn.cocowwy.grpcjava.heartdemo.heart;

public interface HeartReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.cocowwy.heart.HeartReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 serverId = 1;</code>
   */
  int getServerId();

  /**
   * <code>optional string serverName = 2;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>optional string serverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>optional int32 timestamp = 3;</code>
   */
  int getTimestamp();
}
